language: python
python:
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: lonkeknol
  password:
    secure: NRI80rN196jB+SXGsVl9kAzQnqphvAT9cCfNW8oQ9+pq656m7FaZR14rRydxXAcXGzL63smH3WM8nQQGokBTjeMqinFLdv9c+XD8dxmyVjlw3cx4CL+gjhbZ+F8CWjoTRT60u/zHvYTh6LS+n5lCIMX5Z7ZcT7ueKiGqkLcsn4Z0qlinaujHgFjLmhBNjv1apeuKbmjLohWswS+q5JPuo+btw94x6+SbgD5xiRwjDYTo1ZMqFugu45wL6qQAmM0KqkzBmsyleWHEn+cGROx4I3N7nwb99KxPGe2uNVtUl536EvN4jmCkjRHJNcW3qiFT2/hC2e4BuArtXJnciHFtrm++UmZuVnmEGBHg49sEEfxBEQfLKVy5WW9E+7FrtubisOwNZn9ZBgN3FDn+jvYEb0XdbHii2zwsuIZtdhHbG1BoFlVpE0lhKdTm7BXj9XNiYORg1zWscyJ0WNRLBm3TxcVXHaVcgCGWM231r6jviZBSzl9IOAbpA645zlSWn08+sG9YX4iIP3qsaCUZdsPUxurYNedk3sN/+m01MM8GOHmd264JqemS7VywCqgZzK6s243G1LuKwPUgmlMjRDHeXohNlc4JdFqZfZRp6Mx4YDXdGYMLXvm4167PYwXiwIoxUG4XsE+S6fi5qg7n8E8UsG99axpHSyIHGKR19s4dKJw=
  on:
    tags: true
    repo: slicerisk/riskmatrix
    python: 3.7
